cmd.do('')
cmd.do('# ; ')
cmd.do('Bfactors = [];')
cmd.do('# edit the selection below, which is a range of residue numbers here.;')
cmd.do('iterate (resi 133), Bfactors.append(b);')
cmd.do('print( "Average B-factor of residue ", %{1:133 , "   = ", "%.2f" %(reduce(lambda x, y: x + y, Bfactors) / float(len(Bfactors))) );')
