cmd.do('# Edit the selection that is named ligand here.;')
cmd.do('create ligand, /bluComplex/C/A/1101;')
cmd.do('preset.ball_and_stick(selection="ligand");')
cmd.do('util.cbaw ligand;')
cmd.do('set stick_color, white, ligand;')
cmd.do('set valence, off, ligand;')
cmd.do('unset valence;')
cmd.do('# above command is required after using preset;')
cmd.do('set sphere_color, black, elem C and ligand;')
cmd.do('set sphere_color, red, elem O and ligand;')
cmd.do('set sphere_color, blue, elem N and ligand;')
cmd.do('set sphere_color, lightblue, elem F and ligand;')
cmd.do('set stick_radius, 0.12;')
cmd.do('set sphere_quality, 4;')
cmd.do('set cartoon_ring_finder, 4, ligand;')
cmd.do('set cartoon_ring_mode, 3, ligand;')
cmd.do('set cartoon_ring_width, 0.12, ligand;')
cmd.do('set cartoon_ring_transparency, .0, ligand;')
cmd.do('show cartoon, ligand;')
