cmd.do('fetch 1lw9, async=0; ')
cmd.do('zoom (resi 31 or resi 70); ')
cmd.do('preset.technical(selection='all'); ')
cmd.do('bg_color gray70; ')
cmd.do('clip slab, 7,(resi 31 or resi 70);')
cmd.do('rock;')
