cmd.do('show cartoon;')
cmd.do('cartoon putty;')
cmd.do('set cartoon_smooth_loops, 0;')
cmd.do('# The command below may be needed if the above setting does not work.')
cmd.do('# This can happen if using the presets.')
cmd.do('# unset cartoon_smooth_loops; ')
cmd.do('set cartoon_flat_sheets, 0;')
cmd.do('# The command below may be needed if the above setting does not work.')
cmd.do('# This can happen if using the presets.')
cmd.do('# unset cartoon_smooth_loops; ')
cmd.do('set cartoon_smooth_loops,0;')
cmd.do('# The command below may be needed if the above setting does not work.')
cmd.do('# This can happen if using the presets.')
cmd.do('## unset cartoon_smooth_loops;')
