cmd.do('bg_color white;')
cmd.do('hide everything;')
cmd.do('show spheres;')
cmd.do('set  stick_radius = 0.1;')
cmd.do('hide everything, HET;')
cmd.do('show spheres, HET;')
cmd.do('set sphere_quality=3;')
cmd.do('show sticks, resi 1102;')
cmd.do('from pymol import stored;')
cmd.do('# set the stored array equal to the b−values or use your own values; ')
cmd.do('stored.bb = [ ];')
cmd.do('iterate all, stored.bb.append(b);')
cmd.do('# execute a python−block;')
cmd.do('python;')
cmd.do('# scale the b−values;')
cmd.do('M = max(stored.bb);')
cmd.do('scaledBB = map(lambda x: float (x/M), stored.bb);')
cmd.do('count = 0;')
cmd.do('# set the sphere radii independently;')
cmd.do('#[(cmd.set("sphere_scale", x ,"ID %s"%count); count = count + 1) for x in scaledBB];')
cmd.do('for x in scaledBB:')
cmd.do('  cmd.set("sphere_scale", x ,"ID %s"%count)')
cmd.do('  count = count + 1')
cmd.do('python end;')
cmd.do('spectrum b, selection=4gdx;')
cmd.do('space cmyk;')
cmd.do('set specular_intensity , 0.25;')
