cmd.do('framerule=2pt,')
cmd.do('framesep=2mm,')
cmd.do('framesep=2mm,')
cmd.do('breaklines=True,')
cmd.do('baselinestretch=1.2')
cmd.do(']{bash')
cmd.do('{')
cmd.do(' "argv": [')
cmd.do('  "/Applications/PyMOL.app/Contents/bin/python",')
cmd.do('  "-m",')
cmd.do('  "ipykernel_launcher",')
cmd.do('  "-f",')
cmd.do('  "{connection_file"')
cmd.do(' ],')
cmd.do(' "display_name": "pymol.python",')
cmd.do(' "language": "python"')
