cmd.do('from pymol.cgo import *    # get constants')
cmd.do('from pymol import cmd')
cmd.do('')
cmd.do('import math')
cmd.do('')
cmd.do('class Counter:')
cmd.do('    """')
cmd.do('    draw_line')
cmd.do('    source https://www.pymolwiki.org/index.php/Symmetry_Axis')
cmd.do('    ')
cmd.do('    Pymol script copyright Matthew O'Meara and Xavier Ambroggio 2007')
cmd.do('    ')
cmd.do('    Under  GNU Free Documentation License 1.2')
cmd.do('    ')
cmd.do('    Example:')
cmd.do('    ')
cmd.do('    draw_axis(x=18.232, y=17.150, z=9.488,i=-.226639, j=0.708772, k=-.668039, r=1, b=0, g=0, width=1, length=100)')
cmd.do('    ')
cmd.do('    Updated 15 June 2020 ')
cmd.do('    Blaine Mooers')
cmd.do('    ')
cmd.do('    Notes:')
cmd.do('    1) Could be useful for the adding a symmery axis, a ncs axis, or scale bar to a scene.')
cmd.do('    2) The postion (xyz) is the middle of the line, not one end as expected for a vector.')
cmd.do('    3) Another example: draw_axis(x=0, y=0, z=0,i=0, j=0, k=1, r=1, b=0, g=0, width=300, length=96) ')
cmd.do('    4) Changed print statement to Python3 print function.')
cmd.do('    5) Replaced cmd.extend() with function generator.')
cmd.do('    """')
cmd.do('   def __init__(self):')
cmd.do('       self.state = 1')
cmd.do('counter = Counter()')
cmd.do('')
cmd.do('@cmd.extend')
cmd.do('def draw_axis(x=None, y=None, z=None, i=None, j=None, k=None, length=20.0, r=1.0, g=1.0, b=1.0, width=1.0 ):')
cmd.do('   if x == None or y == None or z == None or i == None or j == None or k== None :')
cmd.do('       print('Usage: draw_axis x,y,z, i,k,j, length, r,g,b, width')')
cmd.do('       print('draw a line centered at (x,y,z) with the direction vector (i,j,k)')')
cmd.do('       print('length, color (r,g,b), and width arguments are optional')')
cmd.do('#        print 'For a fun example of the command, run draw_axis_example'')
cmd.do('   else :')
cmd.do('       x,y,z = float(x), float(y), float(z)')
cmd.do('       i,j,k = float(i), float(j), float(k)')
cmd.do('       r,g,b = float(r), float(g), float(b)')
cmd.do('       width = float(width)')
cmd.do('       length = float(length) / 2.0')
cmd.do('')
cmd.do('       x1,y1,z1 = (x+i*length,y+j*length,z+k*length)')
cmd.do('       x2,y2,z2 = (x-i*length,y-j*length,z-k*length)')
cmd.do('')
cmd.do('       obj = [')
cmd.do('           LINEWIDTH, width,')
cmd.do('           BEGIN, LINES,')
cmd.do('')
cmd.do('           COLOR,   r,  g,  b,')
cmd.do('           VERTEX, x1, y1, z1,')
cmd.do('           VERTEX, x2, y2, z2,')
cmd.do('')
cmd.do('           END')
cmd.do('           ]')
cmd.do('')
cmd.do('       cmd.load_cgo(obj,'axis'+str(counter.state))')
cmd.do('       counter.state += 1')
