cmd.do('reinitialize;')
cmd.do('run /Users/blaine/.pymol/startup/dssr_block.py;')
cmd.do('fetch 1ehz, async=0;')
cmd.do('as cartoon;')
cmd.do('set cartoon_ladder_radius, 0.1;')
cmd.do('set cartoon_ladder_color, gray;')
cmd.do('set cartoon_nucleic_acid_mode, 1;')
cmd.do('set cartoon_nucleic_acid_color, orange;')
cmd.do('orient;turn z,30; translate [0,5,0]')
cmd.do('dssr_block;')
cmd.do('png ~/dssrBlock1.png 1600,1600')
