cmd.do('bg_color white;')
cmd.do('show sticks;')
cmd.do('set cartoon_ring_mode, 3;')
cmd.do('set cartoon_ring_finder, 1;')
cmd.do('set cartoon_ladder_mode, 1;')
cmd.do('set cartoon_nucleic_acid_mode, 4;')
cmd.do('set cartoon_ring_transparency, 0.5;')
cmd.do('as cartoon;')
