cmd.do('bg_color white;')
cmd.do('set cartoon_oval_length, 1.85')
cmd.do('set cartoon_oval_width, 0.5')
cmd.do('cartoon oval;')
cmd.do('cartoon dumbbell;')
cmd.do('set cartoon_dumbbell_width, 0.2;')
cmd.do('set cartoon_dumbbell_radius, 0.4;')
cmd.do('set cartoon_ring_mode, 3;')
cmd.do('# set the color of the backbone oval')
cmd.do('set cartoon_nucleic_acid_color, blue;')
cmd.do('select rna_A, resn A;')
cmd.do('select rna_C, resn C;')
cmd.do('select rna_G, resn G;')
cmd.do('select rna_U, resn U;')
cmd.do('select dna_T, resn T;')
cmd.do('color yellow, rna_A;')
cmd.do('color red, rna_C; ')
cmd.do('color gray40, rna_G;')
cmd.do('color palecyan, rna_U;')
cmd.do('color brown, dna_T;')
cmd.do('as cartoon;')
