cmd.do('fetch 3nd3, 3nd3, type=pdb1;')
cmd.do('set all_states, on;')
cmd.do('create chA, 3nd3, 1, 1;')
cmd.do('create chB, 3nd3, 2, 1;')
cmd.do('# colors only the backbone;')
cmd.do('set cartoon_nucleic_acid_color, magenta, chA;')
cmd.do('set cartoon_nucleic_acid_color, orange, chB;')
cmd.do('# color the bases;')
cmd.do('set cartoon_ladder_color,  density, chA;')
cmd.do('set cartoon_ladder_color,  yellow, chB;')
