cmd.do('set bg_rgb, white;')
cmd.do('hide everything, all;')
cmd.do('# Change to the name of your molecular object.;')
cmd.do('show cartoon, 3nd3;')
cmd.do('set cartoon_sampling,1;')
cmd.do('set cartoon_tube_radius, 0.5;')
cmd.do('set cartoon_ladder_mode, 0;')
cmd.do('# Set to 0.0 to turn off transparency;')
cmd.do('set cartoon_transparency, 0.65;')
cmd.do('# The default strick radisu is 0.25. I think it is too thick.;')
cmd.do('set stick_radius 0.12;')
cmd.do('show sticks;')
cmd.do('hide sticks, element H;')
