cmd.do('select rna_A, resn A;')
cmd.do('select rna_C, resn C;')
cmd.do('select rna_G, resn G;')
cmd.do('select rna_U, resn U;')
cmd.do('select dna_T, resn T;')
cmd.do('color yellow, rna_A;')
cmd.do('color red, rna_C; ')
cmd.do('color gray40, rna_G;')
cmd.do('color palecyan, rna_U;')
cmd.do('color brown, dna_T;')
