cmd.do('set bg_rgb, white;')
cmd.do('hide everything, all;')
cmd.do('show cartoon, 3nd3;')
cmd.do('set cartoon_sampling,1;')
cmd.do('set cartoon_tube_radius, 0.5;')
cmd.do('set cartoon_ladder_mode, 0;')
cmd.do('set cartoon_transparency, 0.65;')
cmd.do('set stick_radius 0.12;')
cmd.do('show sticks;')
cmd.do('hide sticks, element H;')
