cmd.do('fetch 4dgr, type=pdb;')
cmd.do('# Make sure to rename map file so that ;')
cmd.do('# the root filename differs from pdb root filename;')
cmd.do('fetch 4dgr,  4dgr_2fofc, type=2fofc;')
cmd.do('fetch 4dgr, 4dgr_fofc, type=fofc;')
cmd.do('select  glycan, resid 200 or resid 469:477;')
cmd.do('isomesh mesh1, 2fofc, 1.0, glycan;')
cmd.do('color density, mesh1;')
cmd.do('isomesh mesh2, fofc, 3.0, glycan;')
cmd.do('color green, mesh2;')
cmd.do('isomesh mesh3, fofc, -3.0, glycan;')
cmd.do('color red, mesh3;')
