cmd.do('load 4dgr.pdb')
cmd.do('# Make sure to rename map file so that ')
cmd.do('# the root filename differs from pdb root filename')
cmd.do('load 4dgr_2fofc.ccp4, 2fofc;')
cmd.do('load 4dgr_fofc.ccp4, fofc;')
cmd.do('select  glycan, resid 200 or (resid 469:477);')
cmd.do('volume mesh1, 2fofc, 1.0, glycan;')
cmd.do('color density, mesh1;')
cmd.do('volume mesh2, fofc, 3.0, glycan;')
cmd.do('color green, mesh2;')
cmd.do('volume mesh3, fofc, -3.0, glycan;')
cmd.do('color red, mesh3;')
